### ISSUE TITLE
MatchError during metadata build

### ISSUE THREAD

**Issue by anildigital** [elixir-lsp/elixir_sense#147]
We are using lot of macros and this error is pretty frequent while using lsp and emacs for Elixir

```bash
warning: MatchError during metadata build: no match of right hand side value: ["Service", "Proto", "OurFramework", "Global", "Context"]
  (elixir_sense 2.0.0) lib/elixir_sense/core/introspection.ex:1163: anonymous fn/2 in ElixirSense.Core.Introspection.expand_alias/2
  (elixir 1.12.3) lib/enum.ex:3862: Enum.find_list/3
  (elixir_sense 2.0.0) lib/elixir_sense/core/introspection.ex:1162: ElixirSense.Core.Introspection.expand_alias/2
  (elixir_sense 2.0.0) lib/elixir_sense/core/metadata_builder.ex:1393: ElixirSense.Core.MetadataBuilder.get_binding_type/2
  (elixir_sense 2.0.0) lib/elixir_sense/core/metadata_builder.ex:1382: ElixirSense.Core.MetadataBuilder.get_binding_type/2
  (elixir_sense 2.0.0) lib/elixir_sense/core/metadata_builder.ex:762: ElixirSense.Core.MetadataBuilder.pre/2
  (elixir_sense 2.0.0) lib/elixir_sense/core/metadata_builder.ex:55: anonymous fn/3 in ElixirSense.Core.MetadataBuilder.safe_call/1
  (elixir 1.12.3) lib/macro.ex:483: anonymous fn/4 in Macro.do_traverse_args/4
```

**Comment by lukaszsamson** [comment]
That’s expected. Elixir sense works on AST level and only handles some macros. It would be an issue if it crashed on macro free code.
