### ISSUE TITLE
Exception when trying to get docs about functions with metadata

### ISSUE THREAD

**Issue by fuelen** [elixir-lsp/elixir_sense#158]
I got this exception when I tried to get docs about the function from Ecto.
```
elixirls: -32000: an exception was raised:
    ** (FunctionClauseError) no function clause matching in ElixirSense.Core.Introspection.get_metadata_entry_md/1
        (elixir_sense 2.0.0) lib/elixir_sense/core/introspection.ex:392: ElixirSense.Core.Introspection.get_metadata_entry_md({:group, "Schema API"})
        (elixir 1.13.2) lib/enum.ex:1597: anonymous fn/3 in Enum.map/2
        (stdlib 3.17) maps.erl:410: :maps.fold_1/3
        (elixir 1.13.2) lib/enum.ex:2408: Enum.map/2
        (elixir_sense 2.0.0) lib/elixir_sense/core/introspection.ex:381: ElixirSense.Core.Introspection.get_metadata_md/1
        (elixir_sense 2.0.0) lib/elixir_sense/core/introspection.ex:304: anonymous fn/4 in ElixirSense.Core.Introspection.get_func_docs_md/2
        (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir_sense 2.0.0) lib/elixir_sense/core/introspection.ex:281: ElixirSense.Core.Introspection.get_func_docs_md/2
```

Ecto uses `:group` key for grouping functions in ex_doc
https://github.com/elixir-ecto/ecto/blob/3ee206b63c13272f0d7a5d48c37dbc1045f07ea0/lib/ecto/repo.ex#L1540

according to `ex_doc` docs, arbitrary key can be used in `@doc`, so `get_metadata_entry_md` function should fall back to `nil` for any unknown keys
https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html#module-grouping-functions

**Comment by DominikM** [comment]
I ended up writing a quick fix for this without reading through the issues first (d'oh!). It's at #159
