### ISSUE TITLE
Definition crash on __MODULE__.Submodule

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#248]
```
** (FunctionClauseError) no function clause matching in ElixirSense.Core.SurroundContext.to_binding/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/surround_context.ex:6: ElixirSense.Core.SurroundContext.to_binding({:alias, {:local_or_var, ~c"__MODULE__"}, ~c"A"}, SomeCallee)
    (elixir_sense 2.0.0) lib/elixir_sense/providers/docs.ex:35: ElixirSense.Providers.Docs.all/3
    (elixir_sense 2.0.0) lib/elixir_sense.ex:71: ElixirSense.docs/3
    (language_server 0.15.1) lib/language_server/providers/hover.ex:24: ElixirLS.LanguageServer.Providers.Hover.hover/4
    (language_server 0.15.1) lib/language_server/server.ex:834: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```

**Comment by lukaszsamson** [comment]
Fixed in https://github.com/elixir-lsp/elixir_sense/pull/253
