### ISSUE TITLE
Definition provider does not work for nested phoenix scopes

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#284]
```
[Error - 20:24:22] Request textDocument/definition failed.
  Message: an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

        (erts 13.2.2.4) :erlang.binary_to_existing_atom("Elixir.MyApp.BackOffice.Elixir", :utf8)
        (elixir 1.16.0) src/elixir_aliases.erl:139: :elixir_aliases.safe_concat/1
        (elixir_sense 2.0.0) lib/elixir_sense/plugins/phoenix/scope.ex:14: ElixirSense.Plugins.Phoenix.Scope.within_scope/2
        (elixir_sense 2.0.0) lib/elixir_sense/providers/definition.ex:252: ElixirSense.Providers.Definition.get_module/4
        (elixir_sense 2.0.0) lib/elixir_sense/providers/definition.ex:179: ElixirSense.Providers.Definition.do_find_function_or_module/6
        (language_server 0.18.0) lib/language_server/providers/definition.ex:16: ElixirLS.LanguageServer.Providers.Definition.definition/5
        (language_server 0.18.0) lib/language_server/server.ex:1189: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
        ```

**Comment by lukaszsamson** [comment]
@gugahoa would you mind looking into that?

**Comment by gugahoa** [comment]
Can you share the snippet?

**Comment by lukaszsamson** [comment]
@gugahoa it crashes when cursor is over `PageController` in
```
scope "/", MyApp.BackOffice do
    scope "/some" do
      scope "/other" do
        get "/", PageController, :index
      end
    end
end
```

It also crashes over all atoms, e.g. over `:index`, ':api_authenticated', `:create` in
```
scope "/", MyApp.BackOffice do
    get "/", PageController, :index
    pipe_through [:api_authenticated]
    resources "/some", SomeController,
      only: [:new, :create]
end
```
with a slightly different stacktrace
```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

    (erts 13.2.2.4) :erlang.binary_to_existing_atom("Elixir.MyApp.BackOffice.create", :utf8)
    (elixir 1.16.0) src/elixir_aliases.erl:139: :elixir_aliases.safe_concat/1
    (elixir_sense 2.0.0) lib/elixir_sense/providers/definition.ex:179: ElixirSense.Providers.Definition.do_find_function_or_module/6
    (language_server 0.18.0) lib/language_server/providers/definition.ex:16: ElixirLS.LanguageServer.Providers.Definition.definition/5
    (language_server 0.18.0) lib/language_server/server.ex:1189: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```
