### ISSUE TITLE
Error raised on behaviour unquote(__MODULE__) statement

### ISSUE THREAD

**Issue by djeusette** [elixir-lsp/elixir_sense#47]
Hi there,

I am using a behaviour statement in a macro like so:

```
defmacro __using__(opts) do
    quote location: :keep do
      @behaviour unquote(__MODULE__)
      ...
    end
end
```

Unfortunately, it raises this error:

```
Message: an exception was raised:
    ** (ArgumentError) argument error
        :erlang.atom_to_binary({:unquote, [line: 37, column: 18], [{:__MODULE__, [line: 37, column: 26], nil}]}, :utf8)
        (elixir_sense) lib/elixir_sense/core/introspection.ex:552: ElixirSense.Core.Introspection.module_to_string/1
        (elixir_sense) lib/elixir_sense/providers/suggestion.ex:336: anonymous fn/2 in ElixirSense.Providers.Suggestion.find_callbacks/2
        (elixir) lib/enum.ex:2994: Enum.flat_map_list/2
        (elixir_sense) lib/elixir_sense/providers/suggestion.ex:335: ElixirSense.Providers.Suggestion.find_callbacks/2
```

Cheers

**Comment by djeusette** [comment]
Hi @axelson,
I'll try to provide the failing test this week.

**Comment by djeusette** [comment]
Hi @axelson,

By adding the following test in `test/elixir_sense/suggestions_test.exs`, I'm able to reproduce the error.

```
test "should work with unquote(__MODULE__)" do
    buffer = "defmodule Dummy do\n  @doc false\n  defmacro __using__() do\n    quote location: :keep do\n      @behaviour unquote(__MODULE__)\n    end\n  end\n  de\nend\n"
    assert [%{}, %{}] = ElixirSense.suggestions(buffer, 8, 5)
end
```

Let me know if you need anything else.

**Comment by axelson** [comment]
Thanks that's very helpful!
