### ISSUE TITLE
Fails to fetch Timex.parse!/2 docs

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir_sense#92]
```
10:05:05.675 [error] Process #PID<0.16894.1> raised an exception
** (FunctionClauseError) no function clause matching in ElixirSense.Core.Introspection.get_metadata_entry_md/1
    (elixir_sense 1.0.1) lib/elixir_sense/core/introspection.ex:271: ElixirSense.Core.Introspection.get_metadata_entry_md({:delegate_to, {Timex.Parse.DateTime.Parser, :parse!, 2}})
    (elixir 1.10.2) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
    (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
    (elixir 1.10.2) lib/enum.ex:2127: Enum.map/2
    (elixir_sense 1.0.1) lib/elixir_sense/core/introspection.ex:261: ElixirSense.Core.Introspection.get_metadata_md/1
    (elixir_sense 1.0.1) lib/elixir_sense/core/introspection.ex:229: anonymous fn/6 in ElixirSense.Core.Introspection.get_func_docs_md/2
    (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir_sense 1.0.1) lib/elixir_sense/core/introspection.ex:221: ElixirSense.Core.Introspection.get_func_docs_md/2
```

Code:
https://github.com/bitwalker/timex/blob/3.6.1/lib/timex.ex#L475-L483
```elixir
  @doc """
  Same as parse/2 and parse/3, except parse! raises on error.
  See parse/2 or parse/3 docs for usage examples.
  """
  @spec parse!(String.t(), String.t()) :: DateTime.t() | NaiveDateTime.t() | no_return
  @spec parse!(String.t(), String.t(), atom) :: DateTime.t() | NaiveDateTime.t() | no_return
  defdelegate parse!(datetime_string, format_string), to: Timex.Parse.DateTime.Parser
  defdelegate parse!(datetime_string, format_string, tokenizer), to: Timex.Parse.DateTime.Parser
```

**Comment by axelson** [comment]
Thanks!
